### ISSUE TITLE
Configuration is not being loaded from application properties

### ISSUE THREAD

**Issue by bwehrle** [vlingo/vlingo-micronaut#2]
I could not find a way to get the properties defined in micronaut to provide the necessary defaults for vlingo.  The only working property for right now is the world name.  This should be fixed.

**Comment by VaughnVernon** [comment]
@bwehrle Would the others be part of `io.vlingo.actors.Configuration` and thus be implemented in a  `Micronaut` configuration provider?

**Comment by VaughnVernon** [comment]
@graemerocher Would you mind also looking over this `vlingo-micronaut` repo? @bwehrle has done excellent work in implementing this, but I know he'd happily accept your suggestions.

We are also having discussion on where to host the `vlingo-zoom` parts that you already reviewed. @bwehrle Thinks that anything Micronaut specific should be located in this `vlingo-micronaut` rather than `vlingo-zoom`. @kbastani and I tend to agree, but we wondered if you could advise here.

Thanks a bunch!

**Comment by kbastani** [comment]
@bwehrle `vlingo-zoom-server` has auto-configurable classes that populate default properties from `resources/application.yml`. See: https://github.com/vlingo/vlingo-zoom/tree/master/vlingo-zoom-server/src/main/java/io/vlingo/config

**Comment by bwehrle** [comment]
Thanks- found the code that builds the world configuriation- thanks!
 https://github.com/vlingo/vlingo-zoom/blob/master/vlingo-zoom-server/src/main/java/io/vlingo/VlingoScene.java#L49
